services:
  nginx-react:
    container_name: ngixreactapp
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #  - 3000:80
    # no ports forward for cloud  
    # and nginx listener should be 3000 instead of 80
    restart: always
    environment:
      NODE_ENV: production
    networks:
     # - cloudflare1_default             # for solbox.axinars.uk
      - axinarcloud1_default  # for iq.axinar.com
networks:
  #cloudflare1_default:                  # for solbox.axinars.uk
  axinarcloud1_default:       # for iq.axinar.com
    external: true  
    
    
