services:
  nginx-react:
    container_name: ngixreactapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:80
    environment:
      NODE_ENV: production
    networks:
     - cloudflarare-tunnel_default
    # - cloudflare1_default # for cloud  
networks:
  cloudflarare-tunnel_default:
    # - cloudflare1_default # for cloud
    external: true  
    
