version: "3"
services:
  nginx-node:
    container_name: ngixnodeapp
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - "4000:4000"
    # no ports forward for cloud  
    networks:
      - backend_cloudflarare-tunnel_default            # for solbox.axinars.uk
      # - cloudflared_axinar_com_default  # for iq.axinar.com
networks:
  backend_cloudflarare-tunnel_default:                 # for solbox.axinars.uk
    external: true 
  # cloudflared_axinar_com_default:       # for iq.axinar.com
    
