version: "3"
services:
  nginx-node:
    container_name: ngixnodeapp
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - "4000:4000"
    # no ports forward for cloud  
    networks:
      - cloudflarare-tunnel_default # for VM
    # - cloudflare1_default         # for cloud  
networks:
  cloudflarare-tunnel_default:   # for VM
    # cloudflare1_default:      # for cloud
    external: true 
