version: "3"
services:
  nginx-node:
    container_name: ngixnodeapp
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - "4000:4000"
    # no ports forward for cloud  
    networks:
      - cloudflare1_default             # for solbox.axinars.uk
      - cloudflared_axinar_com_default  # for iq.axinar.com
networks:
  cloudflare1_default:                  # for solbox.axinars.uk
  cloudflared_axinar_com_default:       # for iq.axinar.com
    external: true 
