version: "3"
services:
  nginx-node:
    container_name: ngixnodeapp
    build: 
      dockerfile: Dockerfile
      context: .
    # ports:
    #  - "4000:4000"
    # no ports forward for cloud 
    restart: always
    networks:
    #  - cloudflare1_default             # for solbox.axinars.uk
      - axinarcloud1_default  # for iq.axinar.com
networks:
  # cloudflare1_default:                  # for solbox.axinars.uk
  axinarcloud1_default :       # for iq.axinar.com
    external: true 
