version: "3"
services:
  nginx-node:
    container_name: ngixnodeapp
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - "4000:4000"
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
      - ./node_modules:/home/nodejs/node_modules

