version: "3"
services:
  nginx-node:
    container_name: ngixreactapp
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
      - ./node_modules:/home/nodejs/node_modules

