export const En_Str = {
    title: "SolBox Control Panel",
    login: "Login",
    email: "Email",
    Password: "Password",
    login_now: "Login Now",
    forgot_password: "Forgot your Password?",
    register_now: "Register Now",
    login_with_google: "Login with Google",
    register: "Register",
    regist_with_google: "Regist with Google",
    back_login: "Back to Login !",
    user_name: "User Name",
    name: "Name",
    first_name: "First Name",
    last_name: "Last Name",
    phone_number: "Phone Number",
    forgetpassword_txt: "Enter your email and we'll send you instructions to reset your password",
    sen_reset_link: "Send Reset Link",
    resetpassword: "Reset Password",
    confirm_password: "Confirm Password",
    new_password: "New Password",
    language: "Language",
    theme: "Theme",
    dark_mode: "Dark Mode",
    light_mode: "Light Mode",
    devices: "Devices",
    setting: "Setting",
    logout: "Log Out",
    status: "Status",
    schedule: "Schedule",
    share_device: "Share Device",
    today: "Today",
    saved: "Saved",
    add: "Add",
    select_user_type: "Select User Type",
    select: 'Select',
    user: 'User',
    technician: 'Technician',
    select_a_user_type: 'Select a User Type',
    register_was_successful: 'Register was successful',
    register_was_successful_msg: 'The user is created. An email has been sent to your email address. Please verify your email.',
    add_new_device: "Add New Device",
    country: "Country",
    city: "City",
    water_tank_limit: "Water Tank Limit",
    alternative_heat_source_available: "Alternative heat source available",
    type_of_heat_source: "Type of heat source",
    electric_heater: "Electric heater",
    gas_boiler: "Gas boiler",
    diesel_boiler: "Diesel boiler",
    pellet_boiler: "Pellet boiler",
    other: "Other",
    solopanel_max_power: "SoloPanel Max Power",
    name_of_installation: "Name Of Installation",
    heat_resistor_value : "Heat Resistor Value ",
    more_fields: "More Fields",
    intended_use_of_device: "Intended use of device",
    professional: "Professional",
    private: "Private",
    home_use: "home use",
    number_of_occupants: "Number of occupants",
    axinar_boilers_should_contact: "Axinar boilers should contact",
    the_owner: "The owner",
    the_installation_technician: "The installation technician",
    gps_location: "GPS location",
    cancel: "Cancel",
    save: 'Save',
    max_water_temperature_allowed: "Max water temperature allowed from solar power",
    max_water_temperature_alternative: "Max water temperature from alternative heat source",
    price_per: "Price per",
    vacation_period_start: "Vacation period start",
    vacation_period_end: "Vacation period end",
    device_info: "Device Information",
    searching_your_device: "Searching Your Device",
    search: "Search",
    feel_devid_paircode: "Please input your device Id or pairing code",
    please_feel_input: "Please feel the input",
    pairing_failed: "Pairing Failed",
    user_not_exist: "User is not exist"
}