export const En_Str = {
    title: "SolBox Control Panel",
    login: "Login",
    email: "Email",
    Password: "Password",
    login_now: "Login Now",
    forgot_password: "Forgot your Password?",
    register_now: "Register Now",
    login_with_google: "Login with Google",
    register: "Register",
    regist_with_google: "Regist with Google",
    back_login: "Back to Login !",
    user_name: "User Name",
    name: "Name",
    first_name: "First Name",
    last_name: "Last Name",
    phone_number: "Phone Number",
    forgetpassword_txt: "Enter your email and we'll send you instructions to reset your password",
    sen_reset_link: "Send Reset Link",
    resetpassword: "Reset Password",
    confirm_password: "Confirm Password",
    new_password: "New Password",
    language: "Language",
    theme: "Theme",
    dark_mode: "Dark Mode",
    light_mode: "Light Mode",
    devices: "Devices",
    setting: "Setting",
    logout: "Log Out",
    status: "Status",
    schedule: "Schedule",
    share_device: "Share Device",
    today: "Today",
    saved: "Saved"
}