export const Es_Str = {
    title: "Panel de control Solbox",
    login: "Acceso",
    email: "Correo electrónico",
    Password: "Contraseña",
    login_now: "Inicia sesión ahora",
    forgot_password: "¿Olvidaste tu contraseña?",
    register_now: "¡Regístrate ahora!",
    login_with_google: "Iniciar sesión con Google",
    register: "Registro",
    regist_with_google: "Regístrate con Google",
    back_login: "Atrás para iniciar sesión !",
    user_name: "Nombre de usuario",
    name: "Nombre",
    first_name: "Nombre de pila",
    last_name: "Apellido",
    phone_number: "Número de teléfono",
    forgetpassword_txt: "Ingresa tu correo electrónico y te enviaremos instrucciones para restablecer tu contraseña",
    sen_reset_link: "Enviar enlace de reinicio",
    resetpassword: "Restablecer la contraseña",
    confirm_password: "confirmar Contraseña",
    new_password: "Nueva contraseña",
    language: "Idioma",
    theme: "Tema",
    dark_mode: "Modo oscuro",
    light_mode: "Modo de luz",
    devices: "Dispositivos",
    setting: "Configuración",
    logout: "Cerrar sesión",
    status: "Estado",
    schedule: "Cronograma",
    share_device: "Compartir dispositivo",
    today: "Hoy",
    saved: "Salvado",
    add: "Agregar",
    select_user_type: "Seleccionar tipo de usuario",
    select: 'Seleccionar',
    user: 'Usuaria',
    technician: 'Técnica',
    select_a_user_type: 'Seleccione un tipo de usuario',
    register_was_successful: 'Registrarse fue exitosa',
    register_was_successful_msg: 'Se crea el usuario. Se ha enviado un correo electrónico a su dirección de correo electrónico. Por favor verifique su correo electrónico.',
    add_new_device: "Agrega un nuevo dispositivo",
    country: "País",
    city: "Ciudad",
    water_tank_limit: "Límite del tanque de agua",
    alternative_heat_source_available: "Fuente de calor alternativa disponible",
    type_of_heat_source: "Tipo de fuente de calor",
    electric_heater: "Calentador eléctrico",
    gas_boiler: "Caldera de gas",
    diesel_boiler: "Caldera de gasoil",
    pellet_boiler: "Caldera de pellets",
    other: "Otra",
    solopanel_max_power: "SoloPanel Máxima Potencia",
    name_of_installation: "Nombre de la instalación",
    heat_resistor_value : "Valor de la resistencia térmica ",
    more_fields: "Más campos",
    intended_use_of_device: "Uso previsto del dispositivo",
    professional: "Profesional",
    private: "Privada",
    home_use: "uso doméstico",
    number_of_occupants: "Número de ocupantes",
    axinar_boilers_should_contact: "Las calderas Axinar deben contactar",
    the_owner: "El propietario",
    the_installation_technician: "El técnico instalador",
    gps_location: "Ubicación GPS",
    cancel: "Cancelar",
    save: 'Ahorrar',
    save_all: "Salvar a todos",
    max_water_temperature: "Temperatura máxima del agua",
    price_per: "Precio por",
    vacation_period_start: "Inicio del periodo de vacaciones",
    vacation_period_end: "Fin del periodo de vacaciones",
    device_info: "Información del dispositivo",
    searching_your_device: "Buscando su dispositivo, por favor espere...",
    search_your_device: "Busque su dispositivo",
    search: "Buscar",
    feel_devid_paircode: "Ingrese el ID de su dispositivo o el código de emparejamiento",
    please_feel_input: "Por favor, siente la entrada",
    pairing_failed: "Emparejamiento fallido",
    user_not_exist: "La usuario no existe",
    delete: "Borrar",
    action: "Acción",
    shared_users: "Usuarios compartidas",
    already_added: "ya esta agregado",
    device_name: "Nombre del dispositivo",
    saved_successfully: "Guardado exitosamente",
    save_failed: "El guardado ha fallado",
    scheule_option: "Opción de horario",
    weekly_option: "Opción Semanal",
    daily: "A diario",
    weekdays: "Días laborables",
    weekend: "Fin de semana",
    entire_week: "La semana entera",
    add_new_daily_schedule: "Agregar nuevo horario diario",
    start: "Comenzar",
    end: "Fin",
    pairing: "Emparejamiento",
    not_device_matched_ip:"No existe el Dispositivo que coincida con su IP",
    device_list_matched_ip: "Lista de dispositivos coincidentes con IP",
    remove: "Eliminar",
    target_temperature:"Temperatura objetivo",
    Sunday: "Domingo",
    Monday: "Lunes",
    Tuesday: "Martes",
    Wednesday: "Miércoles",
    Thursday: "Jueves",
    Friday: "Viernes",
    Saturday: "Sábado",
    device_data_not_loaded: "Los datos de este dispositivo no están cargados. Intente volver a cargarlos después de unos minutos.",
    want_remove_device:"¿Quieres eliminar este dispositivo?",
    removing: "Quitando"
}