export const Es_Str = {
    title: "Panel de control Solbox",
    login: "Acceso",
    email: "Correo electrónico",
    Password: "Contraseña",
    login_now: "Inicia sesión ahora",
    forgot_password: "¿Olvidaste tu contraseña?",
    register_now: "¡Regístrate ahora!",
    login_with_google: "Iniciar sesión con Google",
    register: "Registro",
    regist_with_google: "Regístrate con Google",
    back_login: "Atrás para iniciar sesión !",
    user_name: "Nombre de usuario",
    name: "Nombre",
    first_name: "Nombre de pila",
    last_name: "Apellido",
    phone_number: "Número de teléfono",
    forgetpassword_txt: "Ingresa tu correo electrónico y te enviaremos instrucciones para restablecer tu contraseña",
    sen_reset_link: "Enviar enlace de reinicio",
    resetpassword: "Restablecer la contraseña",
    confirm_password: "confirmar Contraseña",
    new_password: "Nueva contraseña",
    language: "Idioma",
    theme: "Tema",
    dark_mode: "Modo oscuro",
    light_mode: "Modo de luz",
    devices: "Dispositivos",
    setting: "Configuración",
    logout: "Cerrar sesión",
    status: "Estado",
    schedule: "Cronograma",
    share_device: "Compartir dispositivo",
    today: "Hoy",
    saved: "Salvado"
}