export const Es_Str = {
    title: "Panel de control Solbox",
    login: "Acceso",
    email: "Correo electrónico",
    Password: "Contraseña",
    login_now: "Inicia sesión ahora",
    forgot_password: "¿Olvidaste tu contraseña?",
    register_now: "¡Regístrate ahora!",
    login_with_google: "Iniciar sesión con Google",
    register: "Registro",
    regist_with_google: "Regístrate con Google",
    back_login: "Atrás para iniciar sesión !",
    user_name: "Nombre de usuario",
    name: "Nombre",
    first_name: "Nombre de pila",
    last_name: "Apellido",
    phone_number: "Número de teléfono",
    forgetpassword_txt: "Ingresa tu correo electrónico y te enviaremos instrucciones para restablecer tu contraseña",
    sen_reset_link: "Enviar enlace de reinicio",
    resetpassword: "Restablecer la contraseña",
    confirm_password: "confirmar Contraseña",
    new_password: "Nueva contraseña",
    language: "Idioma",
    theme: "Tema",
    dark_mode: "Modo oscuro",
    light_mode: "Modo de luz",
    devices: "Dispositivos",
    setting: "Configuración",
    logout: "Cerrar sesión",
    status: "Estado",
    schedule: "Cronograma",
    share_device: "Compartir dispositivo",
    today: "Hoy",
    saved: "Salvado",
    add: "Agregar",
    select_user_type: "Seleccionar tipo de usuario",
    select: 'Seleccionar',
    user: 'Usuaria',
    technician: 'Técnica',
    select_a_user_type: 'Seleccione un tipo de usuario',
    register_was_successful: 'Registrarse fue exitosa',
    register_was_successful_msg: 'Se crea el usuario. Se ha enviado un correo electrónico a su dirección de correo electrónico. Por favor verifique su correo electrónico.',
    add_new_device: "Agrega un nuevo dispositivo",
    country: "País",
    city: "Ciudad",
    water_tank_limit: "Límite del tanque de agua",
    alternative_heat_source_available: "Fuente de calor alternativa disponible",
    type_of_heat_source: "Tipo de fuente de calor",
    electric_heater: "Calentador eléctrico",
    gas_boiler: "Caldera de gas",
    diesel_boiler: "Caldera de gasoil",
    pellet_boiler: "Caldera de pellets",
    other: "Otra",
    solopanel_max_power: "SoloPanel Máxima Potencia",
    name_of_installation: "Nombre de la instalación",
    heat_resistor_value : "Valor de la resistencia térmica ",
    more_fields: "Más campos",
    intended_use_of_device: "Uso previsto del dispositivo",
    professional: "Profesional",
    private: "Privada",
    home_use: "uso doméstico",
    number_of_occupants: "Número de ocupantes",
    axinar_boilers_should_contact: "Las calderas Axinar deben contactar",
    the_owner: "El propietario",
    the_installation_technician: "El técnico instalador",
    gps_location: "Ubicación GPS",
    cancel: "Cancelar",
    save: 'Ahorrar',
    max_water_temperature_allowed: "Temperatura máxima del agua permitida con energía solar",
    max_water_temperature_alternative: "Temperatura máxima del agua de una fuente de calor alternativa",
    price_per: "Precio por",
    vacation_period_start: "Inicio del periodo de vacaciones",
    vacation_period_end: "Fin del periodo de vacaciones",
    device_info: "Información del dispositivo"
}