export const Gr_Str = {
    title: "Πίνακας Ελέγχου SolBox",
    login: "Login",
    email: "Email",
    Password: "Κωδικός πρόσβασης",
    login_now: "Σύνδεση τώρα",
    forgot_password: "Ξέχασες τον κωδικό σου;",
    register_now: "Εγγραφή τώρα",
    login_with_google: "Σύνδεση με Google",
    register: "Εγγραφή",
    regist_with_google: "Εγγραφή με Google",
    back_login: "Πίσω στην σελίδα σύνδεσης",
    user_name: "Όνομα χρήστη",
    name: "Όνομα",
    first_name: "Όνομα",
    last_name: "Επίθετο",
    phone_number: "Αριθμός τηλεφώνου",
    forgetpassword_txt: "Γράψτε το e-mail σας και θα σας στείλουμε εκεί οδηγίες ανάκτησης.",
    sen_reset_link: "Αποστολή link ανάκτησης",
    resetpassword: "Επαναφορά κωδικού",
    confirm_password: "Επιβεβαίωση κωδικού",
    new_password: "Νέος κωδικός",
    language: "Γλώσσα",
    theme: "Χρωματικό θέμα",
    dark_mode: "Σκοτεινή λειτουργία",
    light_mode: "Φωτεινή λειτουργία",
    devices: "Συσκευές",
    setting: "Ρυθμίσεις",
    logout: "Αποσύνδεση",
    status: "Κατάσταση",
    schedule: "Πρόγραμμα",
    share_device: "Κοινή Χρήση",
    today: "Σήμερα",
    saved: "Κέρδος",
    add: "Προσθήκη",
    select_user_type: "Επιλέξτε Τύπος χρήστη",
    select: 'Επιλέγω',
    user: 'Χρήστης',
    technician: 'Τεχνικός',
    select_a_user_type: 'Επιλέξτε έναν τύπο χρήστη',
    register_was_successful: 'Η εγγραφή ήταν επιτυχής',
    register_was_successful_msg: 'Ο χρήστης δημιουργείται. Ένα email έχει σταλεί στη διεύθυνση email σας. Επαληθεύστε το email σας.'
}