export const Gr_Str = {
    title: "Πίνακας Ελέγχου SolBox",
    login: "Login",
    email: "Email",
    Password: "Κωδικός πρόσβασης",
    login_now: "Σύνδεση τώρα",
    forgot_password: "Ξέχασες τον κωδικό σου;",
    register_now: "Εγγραφή τώρα",
    login_with_google: "Σύνδεση με Google",
    register: "Εγγραφή",
    regist_with_google: "Εγγραφή με Google",
    back_login: "Πίσω στην σελίδα σύνδεσης",
    user_name: "Όνομα χρήστη",
    name: "Όνομα",
    first_name: "Όνομα",
    last_name: "Επίθετο",
    phone_number: "Αριθμός τηλεφώνου",
    forgetpassword_txt: "Γράψτε το e-mail σας και θα σας στείλουμε εκεί οδηγίες ανάκτησης.",
    sen_reset_link: "Αποστολή link ανάκτησης",
    resetpassword: "Επαναφορά κωδικού",
    confirm_password: "Επιβεβαίωση κωδικού",
    new_password: "Νέος κωδικός",
    language: "Γλώσσα",
    theme: "Χρωματικό θέμα",
    dark_mode: "Σκοτεινή λειτουργία",
    light_mode: "Φωτεινή λειτουργία",
    devices: "Συσκευές",
    setting: "Ρυθμίσεις",
    logout: "Αποσύνδεση",
    status: "Κατάσταση",
    schedule: "Πρόγραμμα",
    share_device: "Κοινή Χρήση",
    today: "Σήμερα",
    saved: "Κέρδος",
    add: "Προσθήκη",
    select_user_type: "Επιλέξτε Τύπος χρήστη",
    select: 'Επιλέγω',
    user: 'Χρήστης',
    technician: 'Τεχνικός',
    select_a_user_type: 'Επιλέξτε έναν τύπο χρήστη',
    register_was_successful: 'Η εγγραφή ήταν επιτυχής',
    register_was_successful_msg: 'Ο χρήστης δημιουργείται. Ένα email έχει σταλεί στη διεύθυνση email σας. Επαληθεύστε το email σας.',
    add_new_device: "Προσθήκη νέας συσκευής",
    country: "Χώρα",
    city: "Πόλη",
    water_tank_limit: "Όριο Δεξαμενής Νερού",
    alternative_heat_source_available: "Διατίθεται εναλλακτική πηγή θερμότητας",
    type_of_heat_source: "Τύπος πηγής θερμότητας",
    electric_heater: "Ηλεκτρική θερμάστρα",
    gas_boiler: "Λέβητας αερίου",
    diesel_boiler: "Λέβητας ντίζελ",
    pellet_boiler: "Λέβητας pellet",
    other: "Αλλα",
    solopanel_max_power: "SoloPanel Max PowerΜέγιστη ισχύς SoloPanel",
    name_of_installation: "Όνομα Εγκατάστασης",
    heat_resistor_value : "Τιμή αντίστασης θερμότητας",
    more_fields: "Περισσότερα πεδία",
    intended_use_of_device: "Προβλεπόμενη χρήση της συσκευής",
    professional: "Επαγγελματίας",
    private: "Ιδιωτικός",
    home_use: "οικιακή χρήση",
    number_of_occupants: "Αριθμός επιβατών",
    axinar_boilers_should_contact: "Οι λέβητες Axinar πρέπει να έρθουν σε επαφή",
    the_owner: "Ο ιδιοκτήτης",
    the_installation_technician: "Ο τεχνικός εγκατάστασης",
    gps_location: "Τοποθεσία GPS",
    cancel: "Ματαίωση",
    save: 'Αποθηκεύσετε',
    save_all: "Αποθήκευση όλων",
    max_water_temperature: "Μέγιστη θερμοκρασία νερού",
    price_per: "Τιμή ανά",
    vacation_period_start: "Έναρξη περιόδου διακοπών",
    vacation_period_end: "Τέλος περιόδου διακοπών",
    device_info: "Πληροφορίες συσκευής",
    searching_your_device: "Αναζήτηση για τη συσκευή σας, περιμένετε...",
    search_your_device: "Αναζήτηση στη συσκευή σας",
    search: "Αναζήτηση",
    feel_devid_paircode: "Εισαγάγετε το αναγνωριστικό της συσκευής σας ή τον κωδικό σύζευξης",
    please_feel_input: "Παρακαλώ αισθανθείτε τη συμβολή",
    pairing_failed: "Η σύζευξη απέτυχε",
    user_not_exist: "Ο χρήστης δεν υπάρχει",
    delete: "Διαγράφω",
    action: "Δράση",
    shared_users: "Κοινόχρηστοι χρήστες",
    already_added: "Έχει ήδη προστεθεί",
    device_name: "Ονομα της συσκευής",
    saved_successfully: "Αποθηκεύτηκε επιτυχώς",
    save_failed: "Η αποθήκευση απέτυχε",
    scheule_option: "Επιλογή χρονοδιαγράμματος",
    weekly_option: "Εβδομαδιαία επιλογή",
    daily: "Καθημερινά",
    weekdays: "εργάσιμες",
    weekend: "σαββατοκύριακο",
    entire_week: "Ολόκληρη την εβδομάδα",
    add_new_daily_schedule: "Προσθήκη νέου ημερήσιου προγράμματος",
    start: "Αρχή",
    end: "Τέλος",
    pairing: "Σύζευξη",
    not_device_matched_ip:"Δεν υπάρχει η Συσκευή που να ταιριάζει με την IP σας",
    device_list_matched_ip: "Λίστα συσκευών αντιστοιχισμένη με IP",
    remove: "Αφαιρώ",
    target_temperature:"Θερμοκρασία στόχου",
    Sunday: "Κυριακή",
    Monday: "Δευτέρα",
    Tuesday: "Τρίτη",
    Wednesday: "Τετάρτη",
    Thursday: "Πέμπτη",
    Friday: "Παρασκευή",
    Saturday: "Σάββατο",
    device_data_not_loaded: "Αυτά τα δεδομένα της συσκευής δεν έχουν φορτωθεί. Δοκιμάστε να φορτώσετε ξανά μετά από λίγα λεπτά"
}