export const It_Str = {
    title: "Pannello di controllo SolBox",
    login: "Login",
    email: "E-mail",
    Password: "Parola d'ordine",
    login_now: "Accedi ora",
    forgot_password: "Hai dimenticato la password?",
    register_now: "Iscriviti ora!",
    login_with_google: "Accedi con Google",
    register: "Registrati",
    regist_with_google: "Registrati con Google",
    back_login: "Torna al login !",
    user_name: "Nome utente",
    name: "Nome",
    first_name: "Nome di battesimo",
    last_name: "Cognome",
    phone_number: "Numero di telefono",
    forgetpassword_txt: "Inserisci la tua email e ti invieremo le istruzioni per reimpostare la password",
    sen_reset_link: "Invia collegamento di reimpostazione",
    resetpassword: "Resetta la password",
    confirm_password: "Conferma password",
    new_password: "nuova password",
    language: "Lingua",
    theme: "Tema",
    dark_mode: "Modalità scura",
    light_mode: "Modalità luce",
    devices: "Dispositivi",
    setting: "Collocamento",
    logout: "Disconnettersi",
    status: "Stato",
    schedule: "Programma",
    share_device: "Condividi dispositivo",
    today: "Oggi",
    saved: "Salvato"
}