export const It_Str = {
    title: "Pannello di controllo SolBox",
    login: "Login",
    email: "E-mail",
    Password: "Parola d'ordine",
    login_now: "Accedi ora",
    forgot_password: "Hai dimenticato la password?",
    register_now: "Iscriviti ora!",
    login_with_google: "Accedi con Google",
    register: "Registrati",
    regist_with_google: "Registrati con Google",
    back_login: "Torna al login !",
    user_name: "Nome utente",
    name: "Nome",
    first_name: "Nome di battesimo",
    last_name: "Cognome",
    phone_number: "Numero di telefono",
    forgetpassword_txt: "Inserisci la tua email e ti invieremo le istruzioni per reimpostare la password",
    sen_reset_link: "Invia collegamento di reimpostazione",
    resetpassword: "Resetta la password",
    confirm_password: "Conferma password",
    new_password: "nuova password",
    language: "Lingua",
    theme: "Tema",
    dark_mode: "Modalità scura",
    light_mode: "Modalità luce",
    devices: "Dispositivi",
    setting: "Collocamento",
    logout: "Disconnettersi",
    status: "Stato",
    schedule: "Programma",
    share_device: "Condividi dispositivo",
    today: "Oggi",
    saved: "Salvato",
    add: "Aggiungere",
    select_user_type: "Seleziona Tipo utente",
    select: 'Selezionare',
    user: 'Utente',
    technician: 'Tecnica',
    select_a_user_type: 'Seleziona un tipo di utente',
    register_was_successful: 'La registrazione è avvenuta con successo',
    register_was_successful_msg: `L'utente viene creato. Un'e-mail è stata inviata al tuo indirizzo e-mail. Verifica la tua email.`,
    add_new_device: "Aggiungi nuovo dispositivo",
    country: "Paese",
    city: "Città",
    water_tank_limit: "Limite del serbatoio dell'acqua",
    alternative_heat_source_available: "Fonte di calore alternativa disponibile",
    type_of_heat_source: "Tipo di fonte di calore",
    electric_heater: "Stufa elettrica",
    gas_boiler: "Caldaia a gas",
    diesel_boiler: "Caldaia a gasolio",
    pellet_boiler: "Caldaia a pellet",
    other: "Altra",
    solopanel_max_power: "SoloPanel Potenza massima",
    name_of_installation: "Nome dell'installazione",
    heat_resistor_value : "Valore della resistenza al calore",
    more_fields: "Altri campi",
    intended_use_of_device: "Uso previsto del dispositivo",
    professional: "Professionale",
    private: "Privato",
    home_use: "uso domestico",
    number_of_occupants: "Numero di occupanti",
    axinar_boilers_should_contact: "Le caldaie Axinar devono contattare",
    the_owner: "Il proprietario",
    the_installation_technician: "Il tecnico installatore",
    gps_location: "Posizione GPS",
    cancel: "Annulla",
    save: 'Salva',
    save_all: "Salva tutto",
    max_water_temperature: "Temperatura massima dell'acqua",
    price_per: "Prezzo per",
    vacation_period_start: "Inizio periodo ferie",
    vacation_period_end: "Fine del periodo di vacanza",
    device_info: "Informazioni sul dispositivo",
    searching_your_device: "Ricerca del tuo dispositivo in corso, attendi...",
    search_your_device: "Cerca il tuo dispositivo",
    search: "Ricerca",
    feel_devid_paircode: "Inserisci l'ID del tuo dispositivo o il codice di associazione",
    please_feel_input: "Per favore senti l'input",
    pairing_failed: "Associazione non riuscita",
    user_not_exist: "L'utente non esiste",
    delete: "Eliminare",
    action: "Azione",
    shared_users: "Utenti condivisi",
    already_added: "È già stato aggiunto",
    device_name: "Nome del dispositivo",
    saved_successfully: "Salvato con successo",
    save_failed: "Il salvataggio non è riuscito",
    scheule_option: "Opzione di pianificazione",
    weekly_option: "Opzione settimanale",
    daily: "Quotidiana",
    weekdays: "Giorni della settimana",
    weekend: "Fine settimana",
    entire_week: "Tutta la settimana",
    add_new_daily_schedule: "Aggiungi un nuovo programma giornaliero",
    start: "Inizio",
    end: "FINE",
    pairing: "accoppiamento",
    not_device_matched_ip:"Non esiste un dispositivo abbinato al tuo IP",
    device_list_matched_ip: "Elenco dispositivi abbinato all'IP",
    remove: "Rimuovere"
}